//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruYumFinal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class MenuItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuItem()
        {
            this.Carts = new HashSet<Cart>();
        }
    
        public int MenuItemId { get; set; }

        [Required]
        [RemoteAttribute("IsItemExists", "MenuItems",
            ErrorMessage = "Item already exist")]
        public string Name { get; set; }

        [Required]
        public double Price { get; set; }
        public bool Active { get; set; }

        [Display(Name = "Date of Launch")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0: yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime DateOfLaunch { get; set; }
        public int CategoryId { get; set; }

        [Display(Name = "Free Delivery")]
        public bool FreeDelivery { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual Category Category { get; set; }
    }
}
